sudo: required
services:
  - docker

script:
  - echo "Build local image"
  - docker build -t devstack .
  - docker images
  - docker run -d -p 80:80 -p 5000:5000 --name my-devstack devstack
  - echo "Wait devstack to start up"
  - sleep 180
  - docker ps -a  
  - docker logs my-devstack
  - docker exec -it my-devstack ps -ef
  - docker stop my-devstack
# - echo "Testing public image on Docker Hub"
#  - docker run -d -p 80:80 -p 5000:5000 --name chrissmall22-devstack chrissmall22/docker-devstack
#  - echo "Wait devstack to start up"
#  - sleep 180
#  - docker ps -a
#  - docker images
#  - echo "Checking devstack"  
#  - docker logs chrissmall22-devstack
#  - docker exec -it chrissmall22-devstack ps -ef
#  - docker stop chrissmall22-devstack
